import FundRaisingForm from '../../../../components/ui/FundRaising/FundRaisingForm';

export const metadata = {
  title: 'Create a Fund Raising Campaign',
  description: 'Generated by create next app',
};

const Page = () => {

  return (
    <div className="event-body">
      <div className="heading">Create a Fund Raising Campaign</div>
      <FundRaisingForm />
    </div>
  );
};

export default Page;