import EventPayment from 'components/ui/MyEvents/EventPayment';
export const metadata = {
  title: 'Payment Page',
  description: 'Generated by create next app',
};

export default async function Page({ params }) {

  const event_id = (await params).id;

  return (
    <div className="event-body">
      <div className="heading">Payment For Event</div>
      {event_id ? (
        <>
          <div className="card border-danger " style={{ maxWidth: '600px', margin:"0 auto" }}>
            <div className="card-body">
              <EventPayment event_id={event_id} />
            </div>
          </div>
        </>
      ) : (
        <p>Event ID not provided. Please go back and select an event.</p>
      )
      }
    </div >
  )
}
