
import './globals.css'; 
import Script from 'next/script';
import Header from '../components/Header'; 
export const metadata = {
    title: 'The Share Page',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
            <div className="body-wrapper">
                <Header/>
                {children}
                <Script src="Script.js" strategy="lazyOnload"/>
                <Script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                    strategy="lazyOnload"
                />
            </div>
        </body>
        </html>
    );
}
