// app/layout.js
import './globals.css'; 
import Header from '../components/Header'; 
import 'bootstrap/dist/css/bootstrap.css'; 
import { SidebarProvider } from '@/Context/SidebarContext';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
    title: 'The Share Page',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
       <SidebarProvider>
            <div className="body-wrapper">
                <Header />
                {children}
            </div>
        </SidebarProvider>
        </body>
        </html>
    );
}
