// app/layout.js
import './globals.css'; 
import Script from 'next/script';
import Header from '../components/Header'; 
import 'bootstrap/dist/css/bootstrap.css'; 
export const metadata = {
    title: 'The Share Page',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
            <div className="body-wrapper">
                <Header />
                {children}
            </div>
        </body>
        </html>
    );
}
