import React from 'react'
import EventView from '../../../../../components/EventView'
export const metadata = {
    title: 'Edit Draft Event',
    description: 'Generated by create next app',
  };
  
export default async function Page({ params }) {
    const slug = (await params).slug
    return (
        <EventView slug={slug} />
 )
  }