import React from 'react'
// import EventView from '../../../../../components/EventView'
export const metadata = {
    title: 'Payment Page',
    description: 'Generated by create next app',
  };
  
export default async function Page({ params }) {
    const slug = (await params).id
    return (
        <div className="payment-page">
        <h1>Payment Page</h1>
        {slug ? (
          <>
            <p>Processing payment for event ID: {slug}</p>
            {/* Add your payment form or components here */}
            <form>
              <label>
                Amount:
                <input type="text" value="35.00" readOnly />
              </label>
              <button type="submit">Pay Now</button>
            </form>
          </>
        ) : (
          <p>Event ID not provided. Please go back and select an event.</p>
        )}
      </div>
 )
  }